version: "3"
services:

    # PHP service
    php:
        build:
         context: .
        # image: phpdocker
        container_name: php
        ports:
            - "9000:9000"
        volumes:
        - ".:/var/www/"
        command: php artisan serve --host=0.0.0.0:9000 --port=9000

